### ISSUE TITLE
Track `hashchange` event

### ISSUE THREAD

**Issue by Shifu462** [GoogleChromeLabs/text-fragments-polyfill#136]
In Chrome, if you set a new text fragment hash programmatically, like
https://github.com/GoogleChromeLabs/text-fragments-polyfill
`location.hash = '#:~:text=module%20of%20util-,functions,-for%20generating%20URLs';`
, the page will be scrolled to the text.

The behavior does not provide such functionality.

**Comment by Shifu462** [comment]
The PR is here: https://github.com/GoogleChromeLabs/text-fragments-polyfill/pull/137.

**Comment by ivan** [comment]
I noticed this as well in Firefox by just changing the `#:~:text=` in the URL bar and pressing Enter. Chrome (tested 108) highlights and scrolls to the new text, while the polyfill does not.

**Comment by tomayac** [comment]
@bokand, what do you think is the right behavior here?

**Comment by bokand** [comment]
There's some context in https://github.com/WICG/scroll-to-text-fragment/issues/74

Given the way STTF is [spec'd](https://wicg.github.io/scroll-to-text-fragment/#navigating-to-text-fragment) and implemented, a hash change should cause a scroll-to-text since it invokes the "scroll to the fragment" algorithm which is where STTF is invoked.

**Comment by tomayac** [comment]
Thanks, @bokand! So @tfmar, are you happy to merge #137?

**Comment by ZiadJ** [comment]
Any reason why this is not merged yet?

**Comment by tomayac** [comment]
@bokand @tfmar is anyone from the team owning this?

**Comment by bokand** [comment]
Apologies for the delay - looks good with a comment I left on the review.

**Comment by Shifu462** [comment]
@bokand Can't find your comment. Could you request changes directly on [the PR](https://github.com/GoogleChromeLabs/text-fragments-polyfill/pull/137), if there are any?

**Comment by bokand** [comment]
Sorry - I forgot to hit "submit". You should see it now
